//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adverts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adverts()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int ID_Объявления { get; set; }
        public int ID_Пользователя { get; set; }
        public string Время_находки { get; set; }
        public string Место_находки { get; set; }
        public string Краткое_описание { get; set; }
        public string Подробное_описание { get; set; }
        public Nullable<bool> Активность { get; set; }
        public byte[] Ссылка_на_изображение { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
